package dao.entity;

import base.BaseDomain;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table m_user
 *
 * @author fury 
 * @date 2017-11-16 22:18:00
 */
public class User extends BaseDomain implements Serializable {
    /**
     * Database Column Remarks:
     *   用户Id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.userId
     *
     * 
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   用户姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.userName
     *
     * 
     */
    private String userName;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.createDateTime
     *
     * 
     */
    private Date createDateTime;

    /**
     * Database Column Remarks:
     *   用户资金
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.money
     *
     * 
     */
    private BigDecimal money;

    /**
     * Database Column Remarks:
     *   大文本备注信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.remark
     *
     * 
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_user
     *
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.userId
     *
     * @return the value of m_user.userId
     *
     * 
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.userId
     *
     * @param userId the value for m_user.userId
     *
     * 
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.userName
     *
     * @return the value of m_user.userName
     *
     * 
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.userName
     *
     * @param userName the value for m_user.userName
     *
     * 
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.createDateTime
     *
     * @return the value of m_user.createDateTime
     *
     * 
     */
    public Date getCreateDateTime() {
        return createDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.createDateTime
     *
     * @param createDateTime the value for m_user.createDateTime
     *
     * 
     */
    public void setCreateDateTime(Date createDateTime) {
        this.createDateTime = createDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.money
     *
     * @return the value of m_user.money
     *
     * 
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.money
     *
     * @param money the value for m_user.money
     *
     * 
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.remark
     *
     * @return the value of m_user.remark
     *
     * 
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.remark
     *
     * @param remark the value for m_user.remark
     *
     * 
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}